name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.3
  weather_animation: ^1.1.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/background/
    - assets/graphics/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_sun.png" # Pfad zu deinem App-Icon
  min_sdk_android: 21 # Mindest-SDK-Version für Android
